### ISSUE TITLE
System Enchantment

### ISSUE THREAD

**Issue by beersanp** [khonsaiinc/aquamarine#35]
via @GGameover303 

![Image](https://github.com/khonsaiinc/aquamarine/assets/152690133/2de90b92-be2c-419a-9fde-e2fe4ad59cc4)

Task

- [x] จัดแสง
- [x] transparent ก่อนขึ้น/หลัง cutscene และ scene
- [x] duplicate DoorNextScene

**Comment by beersanp** [comment]
gen branch ให้ละ เช็คในเว็บ

**Comment by roon2555** [comment]
-ใส่เเสงทุกห้อง(GB L)
-ใส่เเสงที่ตู้กดน้า
-เฟดดำตอนเปลื่ยน scene เเละ cutscene
-ทำ UI บทพูดให้เลื่อนขึ้นเมื่อเรื่มบท

**Comment by roon2555** [comment]
-เมื่อจบบทให้เลื่อน UI ลง

**Comment by beersanp** [comment]
https://github.com/khonsaiinc/aquamarine/pull/36
