### ISSUE TITLE
Scene 5 [Back supermarket]

### ISSUE THREAD

**Issue by beersanp** [khonsaiinc/aquamarine#43]

**Comment by beersanp** [comment]
อันนี้ขาดอะไรอีกปะ

**Comment by GGameover303** [comment]
มันคือไรหว่า

**Comment by beersanp** [comment]
เราสร้างแยก scene ไว้เฉยๆ

แต่ว่า ซีนหลังร้านตอนนี้มันขาดอะไรอีกมะ

**Comment by GGameover303** [comment]
เดี๋ยวเอาไปรวมกับ EP2 เลย

**Comment by GGameover303** [comment]
เดี๋ยวว่าจะลบ EP1 ล่ะ หลัง pull req ไป dev

**Comment by beersanp** [comment]
cool

**Comment by GGameover303** [comment]
แล้วสร้าง branch EP2

**Comment by beersanp** [comment]
คือตอนนี้เพิ่งสร้าง #56 ไปละยึดจาก ep1 ไป เอาไงดี

ช่างมัน เดี๋ยวกด sync จาก dev เอาละกัน

**Comment by beersanp** [comment]
แต่จริงๆ เก็บ ep1 ไว้มันก็ได้แหละ
