### ISSUE TITLE
[Bug Report]: Build 2/28/2024

### ISSUE THREAD

**Issue by NO5TALGI4** [khonsaiinc/aquamarine#47]
**ปัญหาที่เกิดขึ้น**

1. เปลียนเครื่องหมาย interac เป็นปุ่ม E 
2. ตอนเปิดประตูเกิดอาการ Delay ( ตอนเปิดประตูควรจะมี fadeดำ ด้วย )
3. กดไม่รับของแต่ Dialog เป็นการรับของและมีกล่องตั้งอยู่ที่โต๊ะ
4. คุยกับรุ่นพี่เส็จแล้วแต่รุ่นพี่ยังอยู่ที่เดิม ( ตอนคุยเส็จเราจะขยับไม่ได้แปปนึง )
5. Animation เปิดประตูยังคงขึ้นก่อนคัตซีน ทำให้คัตซีนขึ้นก่อน
6. ตอน ฮินะ หันไปทางขวาแล้วคุยกับเคาเตอร์ฮินะยังคงหันไปทางขวาฮินะควรจะหันไปทางซ้ายตอนที่คุยกับเคาเตอร์แล้ว
7. สระจม ตอนยายออกไปแล้วขึ้นว่า “ หลังจกานั้น ” จมคำว่า นั้น 
8. คัตซีนรุ่นพี่เข้าร้านเป็นคัตซีนคนส่งของ
9. ตอนคุยกับรุ่นพี่ในร้านอยู่ดีๆ Dialog ก็ดับไป 
10. ตอนคุยกับรุ่นพี่ในร้านเส็จแล้วเราควรจะขยับตัวได้เลยแต่อันนี้ต้องกดE ก่อน 
11. หลังจากเราออกจากเคาเตอร์ตอนคุยกับรุ่นพี่เส็จถ้าเรากลับเข้าไปใหม่ตัวเราจะสไลด์ไปทางขวาและจะขยับอะไรไม่ได้เลย
12. หลังจากจบคัตซีนยายให้ยายเดินมาจากทางซ้ายแล้วมาที่เคาเตอร์ แทนการโผล่มาที่เคาเตอร์เลย
13. ถ้าเราหันไปทางขวาแล้วคุยกับเคาเตอร์เราจะหันไปทางขวาตลอดแม้เราจะอยู่ที่เคาเตอร์แล้วเราควรจะหันไปทางซ้าย
14. ชื่อรุ่นพี่เป็น ??? และมี Dialog อันนึงชื่อเป็นตัวพิมพ์เล็ก
15. เลือกไม่เปิดกล่องแต่ Dialog ยังเป็นเปิดกล่อง
16. Dialog ตอนคุยกับรุ่นพี่ซ้ำ 2 รอบ
17. กดนอนแล้วภาพดำไปเลย

**Comment by beersanp** [comment]
**ปัญหาที่เกิดขึ้น**

- [x] 1. เปลียนเครื่องหมาย interac เป็นปุ่ม E 
- [x] 2. ตอนเปิดประตูเกิดอาการ Delay ( ตอนเปิดประตูควรจะมี fadeดำ ด้วย )
- [x] 3. กดไม่รับของแต่ Dialog เป็นการรับของและมีกล่องตั้งอยู่ที่โต๊ะ
- [x] 4. คุยกับรุ่นพี่เส็จแล้วแต่รุ่นพี่ยังอยู่ที่เดิม ( ตอนคุยเส็จเราจะขยับไม่ได้แปปนึง )
- [x] 5. Animation เปิดประตูยังคงขึ้นก่อนคัตซีน ทำให้คัตซีนขึ้นก่อน
- [x] 6. ตอน ฮินะ หันไปทางขวาแล้วคุยกับเคาเตอร์ฮินะยังคงหันไปทางขวาฮินะควรจะหันไปทางซ้ายตอนที่คุยกับเคาเตอร์แล้ว
- [x] 7. สระจม ตอนยายออกไปแล้วขึ้นว่า “ หลังจกานั้น ” จมคำว่า นั้น 
- [x] 8. คัตซีนรุ่นพี่เข้าร้านเป็นคัตซีนคนส่งของ
- [x] 9. ตอนคุยกับรุ่นพี่ในร้านอยู่ดีๆ Dialog ก็ดับไป 
- [x] 10. ตอนคุยกับรุ่นพี่ในร้านเส็จแล้วเราควรจะขยับตัวได้เลยแต่อันนี้ต้องกดE ก่อน 
- [x] 11. หลังจากเราออกจากเคาเตอร์ตอนคุยกับรุ่นพี่เส็จถ้าเรากลับเข้าไปใหม่ตัวเราจะสไลด์ไปทางขวาและจะขยับอะไรไม่ได้เลย
- [x] 12. หลังจากจบคัตซีนยายให้ยายเดินมาจากทางซ้ายแล้วมาที่เคาเตอร์ แทนการโผล่มาที่เคาเตอร์เลย
- [x] 13. ถ้าเราหันไปทางขวาแล้วคุยกับเคาเตอร์เราจะหันไปทางขวาตลอดแม้เราจะอยู่ที่เคาเตอร์แล้วเราควรจะหันไปทางซ้าย
- [x] 14. ชื่อรุ่นพี่เป็น ??? และมี Dialog อันนึงชื่อเป็นตัวพิมพ์เล็ก
- [x] 15. เลือกไม่เปิดกล่องแต่ Dialog ยังเป็นเปิดกล่อง
- [x] 16. Dialog ตอนคุยกับรุ่นพี่ซ้ำ 2 รอบ
- [x] 17. กดนอนแล้วภาพดำไปเลย

**Comment by beersanp** [comment]
ได้แก้อะไรไปมั่งอะ ตอนนี้

**Comment by GGameover303** [comment]
1.รอทำ UI
2.ทำแค่ fade ดำ / delay เป็นการดักปุ่มซ้ำ (เสร็จ)
3.แก้แล้ว(เสร็จ)
4.(WIP)
5.ประตูควรเปิดก่อนเพราะ Cutscene //รอความเห็นอีกที
6.(WIP)
7.(WIP)
8.รอเปลี่ยน Video
9.Bug
10. //รอความเห็นอีกที
11.รอแก้
12.(WIP)
13. ข้อ 6(WIP)
14.Bug (resolved), @beersanp 
15.เสร็จแล้ว
16.Bug
17.ทำถึงแค่ตรงนั้น

**Comment by beersanp** [comment]
ข้อแรกยังไม่เปลี่ยนตอนนี้ รอ UI ใหม่งอกออกมา

จะทำหลังอาทิตย์นี้

**Comment by beersanp** [comment]
move into next build
