### ISSUE TITLE
insert image in aquamarine-script

### ISSUE THREAD

**Issue by beersanp** [khonsaiinc/aquamarine#68]
- [x] script (ink) via aquamarine-script
- [ ] animation portrait

**Comment by beersanp** [comment]
เหลือ 2 chapter รอภาพมาที่เหลือเสร็จหมดละ

**Comment by beersanp** [comment]
@roon2555 จริงๆลิมบอกไปว่าไม่ต้องสร้าง branch ก็ได้เพราะว่ายังไงแล้วมันแค่เลื่อน submodules เท่านั้น

หรือว่ามันมีสิ่งอื่นที่ยุ่งนอกจากที่นั่น

**Comment by roon2555** [comment]
ไม่น่ายุ่งกับส่วนอื่นอะ

**Comment by roon2555** [comment]
เเต่กูขอที่ใน branch ที่สร้างเลยละกัน ไม่น่ามีบัญหาอะไรชะ

**Comment by roon2555** [comment]
@beersanp

**Comment by beersanp** [comment]
> เเต่กูขอที่ใน branch ที่สร้างเลยละกัน ไม่น่ามีบัญหาอะไรชะ

มันไม่มีอะใช่ แต่ว่าสร้างในนี้มันมี commit แค่เลื่อน submodule มันเลยไม่ได้จำเป็นเท่าไหร่

จริงๆแค่ทำเสร็จเอา link commit ใน art มาแปะในนี้ก็พอ เผื่อจะไม่ทำวันนี้ก่อนที่จะไปธุระ

**Comment by roon2555** [comment]
อะเค

**Comment by roon2555** [comment]
https://github.com/khonsaiinc/aquamarine/commit/fd2ee33afd1eb20b32610b1aa3fcc5eade349890

**Comment by roon2555** [comment]
https://github.com/khonsaiinc/aquamarineart/commit/3012bb7f9ec434c175d9f59cb9cee01f3ccd6250
https://github.com/khonsaiinc/aquamarineart/commit/1b14299c079f2048477ed721a6ee792012183a23

https://github.com/khonsaiinc/aquamarine-script/commit/590088040c26a1737df1468dd0ebdba0c2c99e05

**Comment by roon2555** [comment]
เหลื่อ C14 ที่ยังไม่ใส่ เห็นมันยังไม่ครบ

**Comment by roon2555** [comment]
@beersanp

**Comment by beersanp** [comment]
github มันบัคไร

เอาเป็นว่าเดี๋ยวค่อย close รอ c14
